### ISSUE TITLE
AttributeError: 'float' object has no attribute 'backward'

### ISSUE THREAD

**Issue by ayushchopra96** [bnulihaixia/Deep_metric#26]
AttributeError: 'float' object has no attribute 'backward'
Cannot run loss.backward()

Can you please help me fix this?

Config: python - 3.6.7; pytorch - 0.4.1

**Comment by jotoy** [comment]
I have the same issue. 
Config: python - 3.6.7; pytorch - 0.4.1

**Comment by hjx950319** [comment]
I have the same issue.

**Comment by erickxgarcia** [comment]
In the case of the Weight loss the problem is:
https://github.com/bnulihaixia/Deep_metric/blob/master/losses/Weight.py#L61 
returns mean_pos_sim, mean_neg_sim, prec, loss
 
and 

https://github.com/bnulihaixia/Deep_metric/blob/master/trainer.py#L36 
reads loss, inter_, dist_ap, dist_an

This is also the case with some of the other loss functions as well.

**Comment by bnulihaixia** [comment]
@erickxgarcia  Thanks for point out this error, I will fix it in these days!

**Comment by bnulihaixia** [comment]
@jotoy @hjx950319 @ayushchopra96 You can fix this bug as @erickxgarcia  point out, and I will update the code in one week.

**Comment by ayushchopra96** [comment]
Thanks. Yeah, I realized that. Made the edit. It worked. The same issue is there with NCALoss as well.
